version: "3.1"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: titan
      MYSQL_DATABASE: titan
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

  backend:
    image: node:latest
    restart: always
    environment:
      NODE_ENV: development
      DB_NAME: titan
      DB_USER: root
      DB_PASSWORD: titan
      DB_HOST: mysql
      DB_DIALECT: mysql
      SERVER_PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "start"]
    ports:
      - "8080:8080"
